######################################################################
# Automatically generated by qmake (3.0) Thu Oct 13 21:20:07 2016
######################################################################

TEMPLATE = app
TARGET = two_sum
INCLUDEPATH += .

# Input
SOURCES += main.c


CONFIG += console
